data:
  raw_data_path: data/raw
  interim_data_path: data/interim
  processed_data_path: data/processed
  feature_path: data/interim/Feat_train.csv
  file_name: train.csv
  id_column: passengerid
  test_size: 0.2
  random_state: 42

model:
  processed_data_path: data/processed
  file_name: train.csv
  model_name: lr
  model_path: models
  trained_model_path: models/lr
  hyperparameters:
    lr:
      C: [0.001, 0.01, 0.1, 1, 10, 100]
      penalty: ['l1', 'l2']
      solver: ['liblinear', 'saga']
      max_iter: [100, 200, 500]
    dt:
      max_depth: [None, 5, 10, 20]
      min_samples_split: [2, 5, 10]
      min_samples_leaf: [1, 2, 4]
      criterion: ['gini', 'entropy']
  grid_search:
    cv: 5
    scoring: accuracy
    n_jobs: -1
    verbose: 1

evaluate:
  model_name: lr
  model_path: models
  trained_model_path: models/lr
  reports_path: reports
  figure_path: reports/figures